### ISSUE TITLE
Copy change on STATSCAST

### ISSUE THREAD

**Issue by DFL-J** [Fourbn/dfl-leaderboard-app#3]
I want to change the following copy that is found here: [Statscast](https://dfl-leaderboard.netlify.app/statscast)

Current Copy: 
"Curious about how the queens are doing?
Click the link to see an individual Queen's stats."

CHANGE TO: 
"Curious how your queens are doing?
Click the Queen to see their individual stats."

![Statscast_Copy](https://user-images.githubusercontent.com/86363494/123149407-3acd0c00-d42f-11eb-815b-6ba1f9903558.png)

**Comment by Fourbn** [comment]
fixed by #4
